version: '3.7'
services:

  flask-app:
    build: ./flask
    container_name: "flask-app"
    environment:
      AppConfig: /app/settings.cfg
      DB_PORT_27017_TCP_ADDR: 27017
      DB: mongodb://localhost:27017/teste
    volumes:
      - ./flask/app:/app:rw
    ports:
      - 5000:5000
    links: 
      - mongodb
    depends_on: 
      - mongodb
  
  mongodb:
    image: mongo 
    container_name: "mongo"
    volumes:
      - ./mongodb/data/db:/data/db
    ports: 
      - 27027:27017
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: users

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  react:
    container_name: "react"
    build:
      context: ./react
      dockerfile: Dockerfile
    volumes:
      - './react:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development